#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tallow
Version  : 1
Release  : 1
URL      : https://github.com/sofar/tallow/releases/download/v1/tallow-1.tar.gz
Source0  : https://github.com/sofar/tallow/releases/download/v1/tallow-1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: tallow-bin
Requires: tallow-config
Requires: tallow-doc
BuildRequires : pkgconfig(libsystemd)

%description
tallow
======
Tallow is a fail2ban/lard replacement that uses systemd's native
journal API to scan for attempted ssh logins, and issues temporary
IP bans for clients that violate certain login patterns.

%package bin
Summary: bin components for the tallow package.
Group: Binaries
Requires: tallow-config

%description bin
bin components for the tallow package.


%package config
Summary: config components for the tallow package.
Group: Default

%description config
config components for the tallow package.


%package doc
Summary: doc components for the tallow package.
Group: Documentation

%description doc
doc components for the tallow package.


%prep
%setup -q -n tallow-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1494133956
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1494133956
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tallow

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/tallow.service

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/tallow/*
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
